### ISSUE TITLE
Layer class does not parse nested fields correctly

### ISSUE THREAD

**Issue by JuhPuur** [KimiNewt/pyshark#102]
I have an issue with the way the Layer class handles Mesh Link Establishment TLVs and nested fields in general. The class stores fields in the dictionary _all_fields, and if it finds any more fields with the same name it ignores or misses them. This leads to the field dictionary containing only a single 'mle.tlv' entry, with only the first showvalue stored. Same for any other fields with the same names. Apparently the Layer class is supposed to append values to the dictionary entry associated with the name, but for some reason it doesn't. The processing also completely loses any nesting and the result is a flat compressed structure of the layer that is useless.

**Comment by xnih** [comment]
I believe this is what I'm seeing with smb.file when multiple files are returned in an smb packet.  I can pull the first one ("."), but the "..", "file 1", "file 2", etc, which all are just smb.file in the find_first2 data field get lost.  Was trying to treat it as an array and hoping I could do a smb.file[x], but smb.file[1] blows up with out of index, so shot that idea down.

printing pkt.smb I can see that it has them all, just can't seem to find a way to access the info.  

So if you happen to figure something out, will be nice to try.

**Comment by xnih** [comment]
Digging through closed issues, it looks like this is addressed, at least for what I needed with the alternate_fields option:
https://github.com/KimiNewt/pyshark/pull/46

Not sure if that is the same issue JuhPuur is complaining about, but it seems to be.

**Comment by JuhPuur** [comment]
It's similar, but it's not a solution. Mesh Link Establishment TLVs(Type, Length, Value) are stored in the MLE layer in an ordered fashion, as collections of fields(in the PDML output, separate field elements with attributes within a field element):
<field name="mle.tlv" showname=...>
    <field name="mle.tlv.type" showname=...>
    <field name="mle.tlv.len" showname=...>
    ...
</field>
Information is lost here when the inner fields are moved to the same level with the containing field. Even if the solution behind the link worked(and it seems it doesn't, with the latest pyshark), because the order would be gone and you couldn't reliably associate one Type with its Length and Value.

Layer._get_all_fields_with_alternates does apparently contain the missing information I was complaining about earlier, but the order is still gone.

Since we're talking about recursive layer fields, the LayerField class would have to(could/should) add a field attribute and set its value by recursing to the inner fields. This is roughly what I've been doing with my temporary non-pyshark solution, but it would be good to have it in pyshark itself.

**Comment by CapnHeiner** [comment]
Chiming in from issue 160, I see this as an issue for any structured data within a pcap. The simplest way to reproduce this is to compare the output of pyshark with "tshark -r file.pcap -T pdml|json" with an offending file.pcap. The tshark implementation is flattening trees, and yes it does now show all fields, but the structure is lost and the ordering is arbitrary to the way the dict hashing turns out, which makes the output fairly useless.

Will keep an eye on this for an update or if will contribute if it's helpful. Thanks.

**Comment by FereshtehGH** [comment]
Hello, I have a pcap file, which contains 2 IP (v4) layers. I am willing to get information in both layers, but PyShark only gives the information in the first layer, although, printing the packet will display both layers. I have tried all_fields attribute, but I still get only the first field as a list:
print(pkt.ip.src.all_fields)
results:
[<LayerField ip.src: 10.10.10.210>]

How can I get information in both IP layers?
